#!/usr/bin/env python3
"""Bakes the reading typeface the EPUB reader can switch to.

Same pipeline, charset and table format as make_fonts.py (which owns the UI
face and the UI_EXTRA_CPS index this shares), so the renderer treats both
families identically. Fonts are vendored under tools/fonts/ -- Literata,
SIL OFL; see THIRD-PARTY.md.

Atkinson Hyperlegible used to be baked here as a third face. It was dropped to
pay for the italics: 92 KB of app flash for a face, against a real italic for
both remaining faces. Its files are no longer vendored; putting it back means
fetching them again and adding one entry to FAMILIES.

Run from the repo root:  python3 tools/make_fonts_read.py > src/fonts_read.h
"""
import os
import sys
import make_fonts as mf

FAMILIES = {
    'LIT': ('tools/fonts/Literata-Regular.ttf',
            'tools/fonts/Literata-Bold.ttf',
            'tools/fonts/Literata-Italic.ttf'),
}


def main():
    print('// GENERATED by tools/make_fonts_read.py -- do not edit by hand.')
    print('//')
    print('// Literata as the second reading face for the EPUB reader, in the')
    print('// same table format and charset as fonts_ui.h.')
    print('#pragma once')
    print('#include "fonts_ui.h"  // FontGlyph/UiFont and UI_EXTRA_CPS')
    print()
    total = 0
    for fam, (reg, bold, ital) in FAMILIES.items():
        # The italic is a separate file, not a shear. If it is missing the
        # bake still produces a working firmware -- the italic tables hold the
        # roman -- but it says so, because a silent fallback here would ship
        # emphasis nobody can see.
        if not os.path.exists(ital):
            print('WARNING: %s missing; %s italic will be the roman face'
                  % (ital, fam), file=sys.stderr)
            ital = reg
        for label, px in mf.SIZES:
            total += mf.emit('%s_%s_REG' % (fam, label), reg, px)
            total += mf.emit('%s_%s_BOLD' % (fam, label), bold, px)
            total += mf.emit('%s_%s_ITAL' % (fam, label), ital, px)
    print('// %d bytes of glyph data.' % total, file=sys.stderr)


if __name__ == '__main__':
    main()
