#!/usr/bin/env python3
"""Bakes the two reading typefaces the EPUB reader can switch to.

Same pipeline, charset and table format as make_fonts.py (which owns the UI
face and the UI_EXTRA_CPS index this shares), so the renderer treats all three
families identically. Fonts are vendored under tools/fonts/ -- Literata and
Atkinson Hyperlegible, both SIL OFL; see THIRD-PARTY.md.

Run from the repo root:  python3 tools/make_fonts_read.py > src/fonts_read.h
"""
import sys
import make_fonts as mf

FAMILIES = {
    'LIT': ('tools/fonts/Literata-Regular.ttf', 'tools/fonts/Literata-Bold.ttf'),
    'ATK': ('tools/fonts/AtkinsonHyperlegible-Regular.otf',
            'tools/fonts/AtkinsonHyperlegible-Bold.otf'),
}


def main():
    print('// GENERATED by tools/make_fonts_read.py -- do not edit by hand.')
    print('//')
    print('// Literata and Atkinson Hyperlegible as reading faces for the EPUB')
    print('// reader, in the same table format and charset as fonts_ui.h.')
    print('#pragma once')
    print('#include "fonts_ui.h"  // FontGlyph/UiFont and UI_EXTRA_CPS')
    print()
    total = 0
    for fam, (reg, bold) in FAMILIES.items():
        for label, px in mf.SIZES:
            total += mf.emit('%s_%s_REG' % (fam, label), reg, px)
            total += mf.emit('%s_%s_BOLD' % (fam, label), bold, px)
    print('// %d bytes of glyph data.' % total, file=sys.stderr)


if __name__ == '__main__':
    main()
