// GENERATED by tools/make_fonts_intl.py -- do not edit by hand.
// Thai (Loma), simplified Chinese GB2312-L1 + JIS-L1 kanji, Korean KS X 1001,
// kana, Vietnamese and European Latin (DejaVu), with signed bearings and real
// advances. ASCII stays in fonts_ui.h; the two meet in gfx.cpp.
#pragma once
#include <pgmspace.h>
#include <stdint.h>

// A glyph that knows where it sits: `left` may be negative (combining marks
// reach back over the previous glyph) and `top` is from the top of the line box.
// Deliberately NOT packed: a 12-byte aligned record keeps the uint32 offset
// on a word boundary, which flash-mapped reads on the S3 want.
struct IntlGlyph {
  uint32_t off;
  int8_t left;
  int8_t top;
  uint8_t w;
  uint8_t h;
  uint8_t adv;
};

struct IntlFace {
  uint16_t box;       // line box the glyphs were baked into
  uint16_t toneDrop;  // px a lone Thai tone mark descends (measured)
  uint32_t count;
  const uint16_t* cps;      // sorted; binary-search me
  const IntlGlyph* glyphs;  // parallel to cps
  const uint8_t* bits;
};

extern const IntlFace INTL_16;
extern const IntlFace INTL_24;
extern const IntlFace INTL_32;
